version: '3.3'

services:
  nginx:
      image: nginx
      volumes:
        - ./data/nginx.conf:/etc/nginx/nginx.conf
        - ./data/sites-available:/etc/nginx/sites-available
        - ./data/sites-enabled:/etc/nginx/sites-enabled
        - ./data/ssl/aura.ren:/etc/ssl/aura.ren
      restart: unless-stopped
      network_mode: host
